-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 22:46:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Class_Schedule_Management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Class_Schedule_Management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Class_Schedule_Management` DEFAULT CHARACTER SET utf8 ;
USE `Class_Schedule_Management` ;

-- -----------------------------------------------------
-- Table `Class_Schedule_Management`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Schedule_Management`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `Class_Schedule_Management`.`Teacher` (
  `teacherId` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`teacherId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Schedule_Management`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Schedule_Management`.`Class` ;

CREATE TABLE IF NOT EXISTS `Class_Schedule_Management`.`Class` (
  `classId` VARCHAR(10) NOT NULL,
  `className` VARCHAR(10) NULL,
  PRIMARY KEY (`classId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Schedule_Management`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Schedule_Management`.`Student` ;

CREATE TABLE IF NOT EXISTS `Class_Schedule_Management`.`Student` (
  `studentId` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `classId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`studentId`),
  INDEX `fk_Student_Class_idx` (`classId` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Class`
    FOREIGN KEY (`classId`)
    REFERENCES `Class_Schedule_Management`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Schedule_Management`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Schedule_Management`.`Subject` ;

CREATE TABLE IF NOT EXISTS `Class_Schedule_Management`.`Subject` (
  `subjectId` VARCHAR(10) NOT NULL,
  `subjectName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`subjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class_Schedule_Management`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class_Schedule_Management`.`Course` ;

CREATE TABLE IF NOT EXISTS `Class_Schedule_Management`.`Course` (
  `courseId` VARCHAR(10) NOT NULL,
  `day` VARCHAR(3) NOT NULL,
  `startTime` VARCHAR(5) NOT NULL,
  `endTime` VARCHAR(5) NOT NULL,
  `teacherId` INT NOT NULL,
  `subjectId` VARCHAR(10) NOT NULL,
  `classId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`courseId`),
  INDEX `fk_course_Teacher1_idx` (`teacherId` ASC) VISIBLE,
  INDEX `fk_Course_Subject1_idx` (`subjectId` ASC) VISIBLE,
  INDEX `fk_Course_Class1_idx` (`classId` ASC) VISIBLE,
  CONSTRAINT `fk_course_Teacher1`
    FOREIGN KEY (`teacherId`)
    REFERENCES `Class_Schedule_Management`.`Teacher` (`teacherId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Subject1`
    FOREIGN KEY (`subjectId`)
    REFERENCES `Class_Schedule_Management`.`Subject` (`subjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Class1`
    FOREIGN KEY (`classId`)
    REFERENCES `Class_Schedule_Management`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
